apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-mxemlhdd
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-mxemlhdd:9a5123943f01127f26ae3df936506ab67da5f54f@sha256:0d7509f28b8a3b69701f22e1501cdedb4efcdede5413fc7f394132dfb94bc6ec
        name: container-image  
